import React from 'react';
import { 
  Target, 
  Users, 
  Lightbulb, 
  Award, 
  Globe, 
  Heart, 
  Shield, 
  Zap 
} from 'lucide-react';
import './AboutPage.css';

const AboutPage = () => {
  const sections = [
    {
      icon: <Target size={48} />,
      title: 'Our Mission',
      description: 'To democratize video creation by making professional-quality content accessible to everyone, regardless of their technical skills or budget.',
      details: 'We believe that everyone has a story to tell and deserves the tools to tell it beautifully. Our mission is to break down the barriers that prevent creative individuals from producing high-quality video content.'
    },
    {
      icon: <Users size={48} />,
      title: 'Our Team',
      description: 'A diverse group of AI researchers, video experts, and creative professionals working together to revolutionize content creation.',
      details: 'Our team combines decades of experience in artificial intelligence, computer vision, and video production. We come from leading tech companies and creative agencies, united by our passion for making video creation accessible to everyone.'
    },
    {
      icon: <Lightbulb size={48} />,
      title: 'Innovation',
      description: 'We leverage cutting-edge AI technology to understand context, emotion, and creative intent in ways never before possible.',
      details: 'Our proprietary AI models have been trained on millions of hours of professional video content, enabling them to understand not just what you want to create, but how to make it compelling and engaging.'
    },
    {
      icon: <Award size={48} />,
      title: 'Quality',
      description: 'We maintain the highest standards in everything we do, from our AI models to our user experience and customer support.',
      details: 'Every video generated by our platform undergoes rigorous quality checks and optimization processes. We continuously improve our algorithms based on user feedback and the latest advances in AI technology.'
    },
    {
      icon: <Globe size={48} />,
      title: 'Global Impact',
      description: 'We serve creators, businesses, and educators in over 50 countries, helping them reach their audiences with compelling video content.',
      details: 'From small businesses in rural areas to multinational corporations, our platform has enabled thousands of organizations to create professional video content that would have been impossible or prohibitively expensive before.'
    },
    {
      icon: <Heart size={48} />,
      title: 'Community',
      description: 'We foster a vibrant community of creators who share knowledge, inspiration, and support for each other\'s creative journeys.',
      details: 'Our community features include collaborative projects, shared templates, and regular challenges that bring creators together. We believe that creativity thrives in community, and we provide the tools and spaces for that to happen.'
    },
    {
      icon: <Shield size={48} />,
      title: 'Privacy & Security',
      description: 'Your creative work and personal data are protected with enterprise-grade security measures and privacy-first design principles.',
      details: 'We implement end-to-end encryption, regular security audits, and strict data protection protocols. Your content remains yours, and we never use your creative work to train our models without explicit permission.'
    },
    {
      icon: <Zap size={48} />,
      title: 'Future Vision',
      description: 'We\'re building the future of content creation, where AI and human creativity work together to produce unprecedented results.',
      details: 'Our roadmap includes advanced features like real-time collaboration, voice-to-video generation, and integration with emerging technologies like VR and AR. We\'re committed to staying at the forefront of innovation in creative AI.'
    }
  ];

  return (
    <div className="about-page">
      <div className="about-hero">
        <div className="container">
          <div className="hero-content">
            <h1 className="hero-title">
              About
              <span className="gradient-text"> AI Video Editor</span>
            </h1>
            <p className="hero-description">
              We're revolutionizing video creation by combining the power of artificial intelligence 
              with intuitive design, making professional-quality content accessible to everyone.
            </p>
          </div>
        </div>
      </div>

      <div className="about-sections">
        {sections.map((section, index) => (
          <div key={index} className={`about-section ${index % 2 === 0 ? 'even' : 'odd'}`}>
            <div className="container">
              <div className="section-content">
                <div className="section-icon">
                  {section.icon}
                </div>
                <div className="section-text">
                  <h2 className="section-title">{section.title}</h2>
                  <p className="section-description">{section.description}</p>
                  <p className="section-details">{section.details}</p>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="about-cta">
        <div className="container">
          <div className="cta-content">
            <h2 className="cta-title">Ready to Join Our Mission?</h2>
            <p className="cta-description">
              Start creating amazing videos today and be part of the creative revolution.
            </p>
            <div className="cta-buttons">
              <a href="/signup" className="btn-primary btn-large">
                Get Started Free
              </a>
              <a href="/contact" className="btn-secondary btn-large">
                Contact Us
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;